import ErrorCatcher as ec

ec.run_file_with_error_catching("Test.py")

# print("Did not exit the program!")
